from app.schemas.allergy import Allergy, AllergyBase, AllergyCreate, AllergyInDBBase
from app.schemas.appointment import Appointment, AppointmentBase, AppointmentInDBBase, AppointmentCreate
from app.schemas.basic_health import BasicHealth, BasicHealthBase, BasicHealthInDBBase, BasicHealthCreate
from app.schemas.bill import Bill, BillBase, BillCreate, BillInDBBase
from app.schemas.doctor_note import DoctorNote, DoctorNoteBase, DoctorNoteCreate, DoctorNoteInDBBase
from app.schemas.emergency_contact import EmergencyContact, EmergencyContactBase, EmergencyContactInDBBase, EmergencyContactCreate
from app.schemas.prescription import Prescription, PrescriptionBase, PrescriptionInDBBase, PrescriptionCreate
from app.schemas.user import User, UserBase, UserCreate, UserInDBBase
from app.schemas.vaccination import Vaccination, VaccinationBase, VaccinationInDBBase, VaccinationCreate
